# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
includes = [ "*.nix"]

[formatter.shell]
command = "shfmt"
options = [
    "-i",
    "2",  # indent 2
    "-s",  # simplify the code
    "-bn", # Binary ops like && and | may start a line
    "-ci", # Switch cases will be indented
    "-w",  # write back to the file
]
includes = ["*.sh"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]
